### ISSUE TITLE
Nginx replies with error 403 on every resource and redirects to index.php

### ISSUE THREAD

**Issue by jtcressy** [tobru/nextcloud-openshift#1]
http://imgur.com/PpPnxdC

Image above of configured nextcloud instance with console catching all of the 403 errors. 

I suspect the nginx.conf is not correct but I don't know where to start diagnosing it.

**Comment by tobru** [comment]
Hi @jtcressy. I have updated the template to use the modified image until the upstream issue https://github.com/nextcloud/docker/issues/107 is solved. Would you mind to try again?
