### ISSUE TITLE
Fails to deploy on OpenShift Online

### ISSUE THREAD

**Issue by LorbusChris** [tobru/nextcloud-openshift#2]
On OpenShift Online the nginx deployment fails with the following error:
```
Cannot create build config "nginx". buildconfigs "nginx" is forbidden: build strategy Docker is not allowed.
```
I believe the [layered nginx image](https://github.com/tobru/nextcloud-openshift/blob/master/Dockerfile) needs to be built and pushed to a registry for Online to be able to consume it. Any ideas how to solve this elegantly, possibly without the overhead of manually maintaining a build of that image in a registry?

Could we maybe use the nginx image directly?
At first glance, it seems to me the config file as as ConfigMap could be mounted over the built-in file as a Volume. 
For the extra volume declared in that Dockerfile I am wondering if it wouln't suffice to only specify that in the template?
I am unclear about the permissions, however.

Please feel free to close if you feel this issue doesn't belong here!
Cheers, Chris

**Comment by tobru** [comment]
I'm also not really happy how I've done this Nginx customization. It would be great to use an "official" Nginx image and just configure it using a ConfigMap. I'll keep this issue open and will do some more research as I find time for it. Or if you want to work on it, I'm happy to accept PRs.

**Comment by tobru** [comment]
Oh I forgot to mention that there is already an automated build of the customized Nginx image: https://hub.docker.com/r/tobru/nextcloud-openshift-nginx/. But I'll look for a more elegant solution nevertheless.

I just saw that there is an official Nginx image for OpenShift: https://github.com/nginxinc/openshift-nginx

**Comment by LorbusChris** [comment]
Thanks for the quick response!
The Nginx people are using that image for their Nginx [APB (Ansible Playbook Bundle) ](https://github.com/nginxinc/nginx-oss-apb/blob/master/roles/provision-nginx-oss-apb/tasks/main.yml) which is like a more flexible, powerful OpenShift Template for use with the upcoming Service Catalog (using Ansible Service Broker instead of the Template Broker).

Q is can a Template create and assign values to a ConfigMap object?

**Comment by LorbusChris** [comment]
Closing due to lack of priority. Feel free to reopen if needed :)
