### ISSUE TITLE
permission of the data directory

### ISSUE THREAD

**Issue by holgerkoch** [tobru/nextcloud-openshift#4]
Hello,

i followed your guide and it works really good. There was only one problem. Our openshift is on AWS. So we can only use EFS storage for readwritemany access. But it seems to work.

Unfortunately after the complete installation i got a error message, that my data directory is readable for the world and i should set it to 0770. 

"Ihr Datenverzeichnis kann von anderen Benutzern gelesen werden
Bitte ändern Sie die Berechtigungen auf 0770, so dass das Verzeichnis nicht von anderen Benutzern angezeigt werden kann."

But this is not so easy, because it es a mount of the persistant storage. 

I have no name!@nextcloud-2-s74ff:/var/www/html$ ls -la /var/www/html/data
total 84
drwxrws--x.  4 root            40000  6144 Oct 26 09:26 .
drwxrwsrwx. 15 root       1000810000  4096 Oct 26 09:10 ..
-rw-r--r--.  1 1000810000      40000   324 Oct 26 09:16 .htaccess
-rw-r--r--.  1 1000810000      40000     0 Oct 26 09:16 .ocdata

Can you tell me, how did you solve this problem?

best regards

Holger

**Comment by tobru** [comment]
Yeah, I also faced this issue and did not yet find a solution... I guess this is something which needs to be changed in Nextcloud, but I'm unsure id this is feasible.

**Comment by holgerkoch** [comment]
Maybe this is what we need: https://github.com/nextcloud/server/issues/3245

Best regards

Holger

**Comment by tobru** [comment]
That's exactly the issue I was looking for, thanks for pointing out. In the meantime I'm thinking about adding some patching mechanism to the `DeploymentConfiguration` by using an [init container](https://docs.openshift.com/container-platform/3.6/architecture/core_concepts/pods_and_services.html#pods-services-init-containers) so that we have a temporary workaround. As I'm now on vacation, it will take some time. If you have time to work on it, I'm happy to accept PRs =)

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/issues/3245 is fixed in 13 and will also get a backport to 12.0.5

**Comment by patlachance** [comment]
@holgerkoch we're running OpenShift on AWS as well and use [GlusterFS](https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.3/html-single/container-native_storage_for_openshift_container_platform/) for ReadWriteMany volumes and it works as expected. It can be deployed on your OpenShift cluster as a [Cloud-Native Storage](https://docs.openshift.com/container-platform/3.7/install_config/install/advanced_install.html#advanced-install-glusterfs-persistent-storage) service or you can connect to an external GlusterFS cluster.
